apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-eshop-config
  labels:
    {{- include "catalog-eshop.labels" . | nindent 4 }}
data:
  AUTH_ISSUER_URI: {{ .Values.config.authIssuerUri | quote }}
  AUTH_BROWSER_ISSUER_URI: {{ .Values.config.authBrowserIssuerUri | quote }}
  FRONTEND_ORIGIN: {{ .Values.config.frontendOrigin | quote }}
  API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
  OAUTH_CLIENT_ID: {{ .Values.config.oauthClientId | quote }}
  OAUTH_AUDIENCE: {{ .Values.config.oauthAudience | quote }}
  OAUTH_REDIRECT_URI: {{ .Values.config.oauthRedirectUri | quote }}
  OAUTH_POST_LOGOUT_REDIRECT_URI: {{ .Values.config.oauthPostLogoutRedirectUri | quote }}
  OAUTH_SCOPES: {{ .Values.config.oauthScopes | quote }}
  PAYMENT_PUBLIC_BASE_URL: {{ .Values.config.paymentPublicBaseUrl | quote }}
  PAYMENT_CHECKOUT_RESULT_URL: {{ .Values.config.paymentCheckoutResultUrl | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: {{ .Values.config.jwkSetUri | quote }}
  PAYMENT_BASE_URL: {{ .Values.config.paymentBaseUrl | quote }}
  PAYMENT_WEBHOOK_URL: {{ .Values.config.paymentWebhookUrl | quote }}
  MARIADB_DATABASE: {{ .Values.config.mariadbDatabase | quote }}
  AUTH_MARIADB_DATABASE: {{ .Values.config.authMariadbDatabase | quote }}
  MARIADB_USERNAME: {{ .Values.config.mariadbUsername | quote }}
