apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  labels:
    {{- include "catalog-eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.mariadb.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-jwk-data
  labels:
    {{- include "catalog-eshop.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.authJwk.size }}
