apiVersion: v1
kind: Secret
metadata:
  name: catalog-eshop-secrets
  labels:
    {{- include "catalog-eshop.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_PASSWORD: {{ .Values.secrets.mariadbPassword | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.mariadbRootPassword | quote }}
  PAYMENT_API_SECRET: {{ .Values.secrets.paymentApiSecret | quote }}
  PAYMENT_WEBHOOK_SECRET: {{ .Values.secrets.paymentWebhookSecret | quote }}
